version: '3.4'

services:
  maboke-server:
    image: maboke-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:8080
    networks:
      - mongonetwork
      - mysqlnetwork 
    volumes:
      - .:/app
    environment:
      MYSQL_HOST : mysql
      MYSQL_USER : root
      MYSQL_PASSWORD : secret
      MYSQL_DB : maboke
      CONN_STR: mongodb://root:secret@mongodb
      
networks:
  mongonetwork:
    name: maboke_network  
    external: true 
  mysqlnetwork:
    name: mysql_network  
    external: true  
