version: '3.4'

services:
  maboke-server:
    image: maboke-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:8080
    volumes:
      - .:/app
    environment:
      MYSQL_HOST : mysql
      MYSQL_USER : root
      MYSQL_PASSWORD : secret
      MYSQL_DB : maboke
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
    #env_file:
    #  - .env
  mysqldb:
    image: mysql:8.0
    volumes:
      - maboke-mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    #env_file:
    #  - .env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  mongodb:
    image: mongo
    restart: always
    container_name: mongo-docker
    #env_file:
    #  - .env
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: maboke
#    volumes:
#      - ./workspace:/workspace
#      - type: volume
#        source: mongodb_data_volume
#        target: /data/db

#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - "28081:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: test
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
#      ME_CONFIG_MONGODB_URL: mongo://root:secret@mongo:27017/
#    depends_on:
#      - mongodb


volumes:
  maboke-mysql-data:
#  mongodb_data_volume:
#    driver: local    
