version: '3.4'

services:
  maboke-server:
    image: maboke-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:8080
    volumes:
      - .:/app
    env_file:
      - maboke.env
  mysql:
    image: mysql:8.0
    volumes:
      - maboke-mysql-data:/var/lib/mysql
    env_file:
      - maboke.env
